site_name: "FNT Operations Manual"
theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: pink
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: pink
      accent: light green
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
  features:
    - version
  #   - content.action.share
  #   - content.action.export

nav:
  - Home: index.md
  - Intro: intro.md
  - Development: dev.md
  - Testing: test.md
  - installation: install.md
  - version 1.9.0: version.md
  
# plugins:
#   - search  # Enables search functionality
#   - pdf-export  # Enables PDF export option

extra_javascript:
  - overrides/extra.js

extra_css:
  - overrides/print.css

extra:
  version:
    provider: mike
