name: Deploy to GitHub Pages
on:
  push:
    tags:
      - 'v*'
    # branches:
    #   - main

concurrency:
  group: "pages-deploy"
  cancel-in-progress: true
  
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install mike mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch latest changes from remote
        run: |
          git fetch origin gh-pages

      # - name: Delete version 2.0
      #   run: |
      #     mike delete v2.0 --push
      
      # - name: Rename version 2.0 to 1.0
      #   run: |
      #     mike rename v2.0 v1.0 --push

      - name: Deploy Documentation
        # run: mike deploy v2.0 --push
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Extract version from the Git tag (e.g., 'v1.0.0')
          echo "Deploying version $VERSION"
          mike deploy $VERSION --push

      - name: Set Default Version to the Newly Deployed Version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}  # Extract version from the Git tag
          echo "Setting $VERSION as the default version"
          mike set-default $VERSION --push  # Set the newly deployed version as the default       

      # - name: Set Default Version to latest
      #   run: |
      #     mike set-default latest --push
      
      # - name: Set version 1.0 as default
      #   run: |
      #     mike set-default v1.0 --push      

      # - name: Deploy to GitHub Pages
      #   run: mkdocs gh-deploy --force



# git tag -a v1.6.0 -m "Release version 1.6.0 testing"
# git push origin v1.6.0