name: Deploy to GitHub Pages
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: pip install mike mkdocs-material

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Fetch latest changes from remote
        run: |
          git fetch origin gh-pages

      # - name: Delete version 1.0
      #   run: |
      #     mike remove v1.0 --push
      
      # - name: Rename version 2.0 to 1.0
      #   run: |
      #     mike rename v2.0 v1.0 --push

      - name: Deploy Documentation
        run: mike deploy v2.0 --push

      - name: Set Default Version
        run: |
          mike set-default latest --push
      
      # - name: Set version 1.0 as default
      #   run: |
      #     mike set-default v1.0 --push      

      # - name: Deploy to GitHub Pages
      #   run: mkdocs gh-deploy --force
